export const US_MISSIONS: string[] = [
  // Alabama
  "Alabama Birmingham",
  // Alaska
  "Alaska Anchorage",
  // Arizona
  "Arizona Gilbert",
  "Arizona Mesa",
  "Arizona Phoenix",
  "Arizona Scottsdale",
  "Arizona Tempe",
  "Arizona Tucson",
  // Arkansas
  "Arkansas Little Rock",
  // California
  "California Anaheim",
  "California Arcadia",
  "California Bakersfield",
  "California Carlsbad",
  "California Fresno",
  "California Irvine",
  "California Long Beach",
  "California Los Angeles",
  "California Modesto",
  "California Oakland",
  "California Rancho Cucamonga",
  "California Riverside",
  "California Roseville",
  "California Sacramento",
  "California San Bernardino",
  "California San Diego",
  "California San Fernando",
  "California San Francisco",
  "California San Jose",
  "California Santa Rosa",
  "California Ventura",
  // Colorado
  "Colorado Colorado Springs",
  "Colorado Denver",
  "Colorado Denver South",
  "Colorado Grand Junction",
  // Connecticut
  "Connecticut Hartford",
  // Florida
  "Florida Fort Lauderdale",
  "Florida Jacksonville",
  "Florida Orlando",
  "Florida Tallahassee",
  "Florida Tampa",
  // Georgia
  "Georgia Atlanta",
  "Georgia Atlanta North",
  "Georgia Macon",
  // Hawaii
  "Hawaii Honolulu",
  // Idaho
  "Idaho Boise",
  "Idaho Nampa",
  "Idaho Pocatello",
  "Idaho Twin Falls",
  // Illinois
  "Illinois Chicago",
  "Illinois Chicago West",
  "Illinois Nauvoo",
  // Indiana
  "Indiana Indianapolis",
  // Iowa
  "Iowa Des Moines",
  // Kansas
  "Kansas Wichita",
  // Kentucky
  "Kentucky Louisville",
  // Louisiana
  "Louisiana Baton Rouge",
  "Louisiana Shreveport",
  // Maine
  "Maine Portland",
  // Maryland
  "Maryland Baltimore",
  // Massachusetts
  "Massachusetts Boston",
  // Michigan
  "Michigan Detroit",
  "Michigan Lansing",
  // Minnesota
  "Minnesota Minneapolis",
  // Mississippi
  "Mississippi Jackson",
  // Missouri
  "Missouri Independence",
  "Missouri St. Louis",
  // Montana
  "Montana Billings",
  "Montana Helena",
  // Nebraska
  "Nebraska Omaha",
  // Nevada
  "Nevada Las Vegas",
  "Nevada Las Vegas West",
  "Nevada Reno",
  // New Hampshire / Vermont covered by Maine or Connecticut
  // New Jersey
  "New Jersey Morristown",
  // New Mexico
  "New Mexico Albuquerque",
  "New Mexico Farmington",
  // New York
  "New York New York City",
  "New York New York City North",
  "New York Rochester",
  "New York Utica",
  // North Carolina
  "North Carolina Charlotte",
  "North Carolina Raleigh",
  // North Dakota
  "North Dakota Bismarck",
  // Ohio
  "Ohio Cincinnati",
  "Ohio Cleveland",
  "Ohio Columbus",
  // Oklahoma
  "Oklahoma Oklahoma City",
  "Oklahoma Tulsa",
  // Oregon
  "Oregon Eugene",
  "Oregon Portland",
  "Oregon Salem",
  // Pennsylvania
  "Pennsylvania Philadelphia",
  "Pennsylvania Pittsburgh",
  // South Carolina
  "South Carolina Columbia",
  // South Dakota
  "South Dakota Rapid City",
  // Tennessee
  "Tennessee Knoxville",
  "Tennessee Nashville",
  // Texas
  "Texas Austin",
  "Texas Dallas",
  "Texas Fort Worth",
  "Texas Houston",
  "Texas Houston East",
  "Texas Houston South",
  "Texas Lubbock",
  "Texas McAllen",
  "Texas San Antonio",
  // Utah
  "Utah Layton",
  "Utah Logan",
  "Utah Ogden",
  "Utah Orem",
  "Utah Provo",
  "Utah Salt Lake City",
  "Utah Salt Lake City South",
  "Utah Salt Lake City West",
  "Utah St. George",
  // Virginia
  "Virginia Chesapeake",
  "Virginia Richmond",
  // Washington
  "Washington Everett",
  "Washington Federal Way",
  "Washington Seattle",
  "Washington Spokane",
  "Washington Tacoma",
  "Washington Yakima",
  // West Virginia
  "West Virginia Charleston",
  // Wisconsin
  "Wisconsin Milwaukee",
  // Wyoming
  "Wyoming Casper",
];

export const WORLD_MISSIONS: string[] = [
  // Africa
  "Benin Cotonou",
  "Botswana Gaborone",
  "Cameroon Douala",
  "Cameroon Yaoundé",
  "Cape Verde Praia",
  "Chad N'Djamena",
  "Congo Brazzaville",
  "Congo Kinshasa",
  "Congo Lubumbashi",
  "Congo Mbuji-Mayi",
  "Côte d'Ivoire Abidjan",
  "Côte d'Ivoire Abidjan West",
  "Ethiopia Addis Ababa",
  "Gabon Libreville",
  "Ghana Accra",
  "Ghana Accra West",
  "Ghana Cape Coast",
  "Ghana Kumasi",
  "Ghana Tamale",
  "Kenya Nairobi",
  "Kenya Nairobi East",
  "Liberia Monrovia",
  "Madagascar Antananarivo",
  "Malawi Lilongwe",
  "Mauritius Port Louis",
  "Mozambique Beira",
  "Mozambique Maputo",
  "Namibia Windhoek",
  "Nigeria Abuja",
  "Nigeria Benin City",
  "Nigeria Calabar",
  "Nigeria Enugu",
  "Nigeria Ibadan",
  "Nigeria Lagos",
  "Nigeria Lagos East",
  "Nigeria Owerri",
  "Nigeria Port Harcourt",
  "Nigeria Uyo",
  "Rwanda Kigali",
  "Senegal Dakar",
  "Sierra Leone Freetown",
  "South Africa Cape Town",
  "South Africa Durban",
  "South Africa Johannesburg",
  "South Africa Johannesburg North",
  "Tanzania Dar es Salaam",
  "Togo Lomé",
  "Uganda Kampala",
  "Uganda Kampala West",
  "Zambia Lusaka",
  "Zimbabwe Bulawayo",
  "Zimbabwe Harare",

  // Asia
  "Cambodia Phnom Penh",
  "Hong Kong",
  "India Bangalore",
  "India New Delhi",
  "Indonesia Jakarta",
  "Indonesia Surabaya",
  "Japan Fukuoka",
  "Japan Kobe",
  "Japan Nagoya",
  "Japan Sapporo",
  "Japan Sendai",
  "Japan Tokyo",
  "Japan Tokyo North",
  "Japan Tokyo South",
  "Korea Busan",
  "Korea Daejeon",
  "Korea Seoul",
  "Korea Seoul South",
  "Malaysia Kuala Lumpur",
  "Mongolia Ulaanbaatar",
  "Pakistan Islamabad",
  "Philippines Angeles",
  "Philippines Bacolod",
  "Philippines Baguio",
  "Philippines Butuan",
  "Philippines Cagayan de Oro",
  "Philippines Caloocan",
  "Philippines Cauayan",
  "Philippines Cavite",
  "Philippines Cebu",
  "Philippines Cebu East",
  "Philippines Davao",
  "Philippines Iloilo",
  "Philippines Legazpi",
  "Philippines Lipa",
  "Philippines Makati",
  "Philippines Manila",
  "Philippines Naga",
  "Philippines Olongapo",
  "Philippines Quezon City",
  "Philippines San Fernando",
  "Philippines San Pablo",
  "Philippines Santiago",
  "Philippines Tacloban",
  "Philippines Urdaneta",
  "Philippines Zamboanga",
  "Singapore",
  "Sri Lanka Colombo",
  "Taiwan Taichung",
  "Taiwan Taipei",
  "Thailand Bangkok",

  // Central America & Caribbean
  "Belize/Guatemala Flores",
  "Costa Rica San José",
  "Dominican Republic East",
  "Dominican Republic North",
  "Dominican Republic Santo Domingo",
  "El Salvador San Salvador",
  "El Salvador San Salvador East",
  "El Salvador Santa Ana",
  "Guatemala Guatemala City",
  "Guatemala Guatemala City Central",
  "Guatemala Guatemala City North",
  "Guatemala Guatemala City South",
  "Guatemala Quetzaltenango",
  "Haiti Port-au-Prince",
  "Honduras Comayagua",
  "Honduras San Pedro Sula",
  "Honduras Tegucigalpa",
  "Jamaica Kingston",
  "Nicaragua Managua",
  "Nicaragua Managua South",
  "Panama Panama City",
  "Puerto Rico San Juan",
  "Trinidad and Tobago Port of Spain",

  // Europe
  "Albania Tirana",
  "Armenia/Georgia Yerevan",
  "Austria Vienna",
  "Baltic Tallinn",
  "Belgium/Netherlands Brussels",
  "Bulgaria Sofia",
  "Croatia Zagreb",
  "Czech/Slovak Prague",
  "Denmark Copenhagen",
  "England Birmingham",
  "England Leeds",
  "England London",
  "England London South",
  "England Manchester",
  "Finland Helsinki",
  "France Lyon",
  "France Marseille",
  "France Paris",
  "France Paris East",
  "Germany Berlin",
  "Germany Frankfurt",
  "Germany Hamburg",
  "Germany Munich",
  "Greece Athens",
  "Hungary Budapest",
  "Iceland Reykjavik",
  "Ireland/Northern Ireland Dublin",
  "Italy Catania",
  "Italy Milan",
  "Italy Padova",
  "Italy Rome",
  "Norway Oslo",
  "Poland Warsaw",
  "Portugal Lisbon",
  "Portugal Porto",
  "Romania Bucharest",
  "Russia Moscow",
  "Scotland/Ireland Edinburgh",
  "Serbia Belgrade",
  "Slovenia Ljubljana",
  "Spain Barcelona",
  "Spain Madrid",
  "Spain Málaga",
  "Sweden Stockholm",
  "Switzerland Geneva",
  "Switzerland Zurich",
  "Ukraine Dnipro",
  "Ukraine Kyiv",
  "Wales/England Bristol",

  // Mexico
  "Mexico Aguascalientes",
  "Mexico Cancún",
  "Mexico Chihuahua",
  "Mexico Ciudad de México",
  "Mexico Ciudad de México East",
  "Mexico Ciudad de México North",
  "Mexico Ciudad de México South",
  "Mexico Ciudad Juárez",
  "Mexico Ciudad Obregón",
  "Mexico Culiacán",
  "Mexico Guadalajara",
  "Mexico Guadalajara East",
  "Mexico Hermosillo",
  "Mexico León",
  "Mexico Mérida",
  "Mexico Mexicali",
  "Mexico Monterrey",
  "Mexico Monterrey East",
  "Mexico Monterrey West",
  "Mexico Oaxaca",
  "Mexico Pachuca",
  "Mexico Puebla",
  "Mexico Puebla South",
  "Mexico Querétaro",
  "Mexico Tampico",
  "Mexico Tijuana",
  "Mexico Toluca",
  "Mexico Torreón",
  "Mexico Tuxtla Gutiérrez",
  "Mexico Veracruz",
  "Mexico Villahermosa",
  "Mexico Xalapa",

  // Oceania
  "Australia Adelaide",
  "Australia Brisbane",
  "Australia Melbourne",
  "Australia Perth",
  "Australia Sydney",
  "Fiji Suva",
  "Kiribati Tarawa",
  "Marshall Islands Majuro",
  "Micronesia Guam",
  "New Zealand Auckland",
  "New Zealand Wellington",
  "Papua New Guinea Port Moresby",
  "Samoa Apia",
  "Tonga Nuku'alofa",
  "Vanuatu Port Vila",

  // South America
  "Argentina Buenos Aires",
  "Argentina Buenos Aires City",
  "Argentina Buenos Aires North",
  "Argentina Buenos Aires South",
  "Argentina Buenos Aires West",
  "Argentina Córdoba",
  "Argentina Mendoza",
  "Argentina Neuquén",
  "Argentina Resistencia",
  "Argentina Rosario",
  "Argentina Salta",
  "Bolivia Cochabamba",
  "Bolivia La Paz",
  "Bolivia Santa Cruz",
  "Brazil Belém",
  "Brazil Belo Horizonte",
  "Brazil Belo Horizonte East",
  "Brazil Brasília",
  "Brazil Campinas",
  "Brazil Campo Grande",
  "Brazil Cuiabá",
  "Brazil Curitiba",
  "Brazil Florianópolis",
  "Brazil Fortaleza",
  "Brazil Goiânia",
  "Brazil João Pessoa",
  "Brazil Londrina",
  "Brazil Maceió",
  "Brazil Manaus",
  "Brazil Natal",
  "Brazil Porto Alegre",
  "Brazil Porto Alegre South",
  "Brazil Recife",
  "Brazil Ribeirão Preto",
  "Brazil Rio de Janeiro",
  "Brazil Rio de Janeiro North",
  "Brazil Salvador",
  "Brazil Santa Maria",
  "Brazil Santos",
  "Brazil São Paulo",
  "Brazil São Paulo East",
  "Brazil São Paulo Interlagos",
  "Brazil São Paulo North",
  "Brazil São Paulo South",
  "Brazil Teresina",
  "Brazil Vitória",
  "Chile Antofagasta",
  "Chile Concepción",
  "Chile Rancagua",
  "Chile Santiago",
  "Chile Santiago East",
  "Chile Santiago North",
  "Chile Santiago South",
  "Chile Santiago West",
  "Chile Viña del Mar",
  "Colombia Barranquilla",
  "Colombia Bogotá",
  "Colombia Bogotá North",
  "Colombia Bogotá South",
  "Colombia Cali",
  "Colombia Medellín",
  "Ecuador Guayaquil",
  "Ecuador Guayaquil North",
  "Ecuador Guayaquil South",
  "Ecuador Quito",
  "Ecuador Quito North",
  "Ecuador Quito South",
  "Paraguay Asunción",
  "Paraguay Asunción North",
  "Peru Arequipa",
  "Peru Chiclayo",
  "Peru Cusco",
  "Peru Huancayo",
  "Peru Iquitos",
  "Peru Lima",
  "Peru Lima Central",
  "Peru Lima East",
  "Peru Lima North",
  "Peru Lima South",
  "Peru Piura",
  "Peru Trujillo",
  "Uruguay Montevideo",
  "Venezuela Caracas",
  "Venezuela Maracaibo",
  "Venezuela Valencia",
];

export const ALL_MISSIONS = [...US_MISSIONS, ...WORLD_MISSIONS].sort();
